// Date: 12/21/2012 9:31:11 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package dx.mods.amethyst;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelCow;
import net.minecraft.client.model.ModelQuadruped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.world.World;

public class ModelBeryllope extends ModelCow
{
	public World world;
	
  //fields
    ModelRenderer nose;
    ModelRenderer tail;
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer horn1;
    ModelRenderer horn2;
  
  public ModelBeryllope()
  {
	  textureWidth = 64;
	  textureHeight = 64;
	  
      nose = new ModelRenderer(this, 24, 0);
      nose.addBox(-2F, -1F, -1F, 4, 2, 2);
      nose.setRotationPoint(-0.5F, 6.5F, -14F);
      nose.setTextureSize(64, 64);
      nose.mirror = true;
      setRotation(nose, 0F, 0F, 0F);
      tail = new ModelRenderer(this, 44, 54);
      tail.addBox(-1F, -1F, 0F, 2, 2, 8);
      tail.setRotationPoint(-0.5F, 4F, 8F);
      tail.setTextureSize(64, 64);
      tail.mirror = true;
      setRotation(tail, 0.3490659F, 0F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-3F, -4F, -6F, 6, 8, 6);
      head.setRotationPoint(-0.5F, 4F, -8F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 24, 14);
      body.addBox(-5F, -10F, -7F, 9, 17, 8);
      body.setRotationPoint(0F, 4F, 2F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 1.570796F, 0F, 0F);
      leg1 = new ModelRenderer(this, 0, 14);
      leg1.addBox(-3F, 0F, -2F, 3, 13, 3);
      leg1.setRotationPoint(-2F, 11F, 7F);
      leg1.setTextureSize(64, 64);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 0, 14);
      leg2.addBox(-1F, 0F, -2F, 3, 13, 3);
      leg2.setRotationPoint(2F, 11F, 7F);
      leg2.setTextureSize(64, 64);
      setRotation(leg2, 0F, 0F, 0F);
      leg2.mirror = false;
      leg3 = new ModelRenderer(this, 12, 14);
      leg3.addBox(-3F, 0F, -3F, 3, 14, 3);
      leg3.setRotationPoint(-2F, 10F, -5F);
      leg3.setTextureSize(64, 64);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 12, 14);
      leg4.addBox(-1F, 0F, -3F, 3, 14, 3);
      leg4.setRotationPoint(2F, 10F, -5F);
      leg4.setTextureSize(64, 64);
      setRotation(leg4, 0F, 0F, 0F);
      leg4.mirror = false;
      horn1 = new ModelRenderer(this, 58, 0);
      horn1.addBox(-3.5F, -4F, -4F, 1, 3, 2);
      horn1.setRotationPoint(-0.5F, 2F, -6F);
      horn1.setTextureSize(64, 64);
      horn1.mirror = true;
      setRotation(horn1, -0.0872665F, 0F, 0F);
      horn2 = new ModelRenderer(this, 58, 0);
      horn2.addBox(2.5F, -4F, -4F, 1, 3, 2);
      horn2.setRotationPoint(-0.5F, 2F, -6F);
      horn2.setTextureSize(64, 64);
      horn2.mirror = true;
      setRotation(horn2, -0.0872665F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
	super.render(par1Entity, par2, par3, par4, par5, par6, par7);
	setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    nose.render(par7);
    tail.render(par7);
    head.render(par7);
    body.render(par7);
    leg1.render(par7);
    leg2.render(par7);
    leg3.render(par7);
    leg4.render(par7);
    horn1.render(par7);
    horn2.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
    super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
  }

}
